# Generated by Django 5.0.6 on 2024-07-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_especialidad_alter_customuser_managers_alumno_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Profesor'), (3, 'Alumno'), (4, 'Tutor')], default=3),
        ),
    ]
