# Generated by Django 5.0.6 on 2024-07-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
    ]
